backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets/images"
public_folder: "_astro"

locale: 'pl'

collections:
  - name: "countries-en" # Used in routes, e.g., /admin/collections/blog
    label: "Countries EN" # Used in the UI
    folder: "src/content/country/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "/en/{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sort order", name: "sortOrder", widget: "number"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "countries-pl" # Used in routes, e.g., /admin/collections/blog
    label: "Countries PL" # Used in the UI
    folder: "src/content/country/pl" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "/pl/{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sort order", name: "sortOrder", widget: "number"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages-en"
    label: "Pages EN"
    files:
      - file: "src/pages/en/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Welcome", name: "welcome", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
