backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets/images"
public_folder: "_astro"

collections:
  - name: "countries-en" # Used in routes, e.g., /admin/collections/blog
    label: "Countries EN" # Used in the UI
    label_singular: "Country EN"
    folder: "src/content/country/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sort order", name: "sortOrder", widget: "number" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "countries-pl" # Used in routes, e.g., /admin/collections/blog
    label: "Countries PL" # Used in the UI
    label_singular: "Country PL"
    folder: "src/content/country/pl" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sort order", name: "sortOrder", widget: "number" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages-en"
    label: "Pages EN"
    files:
      - file: "src/pages/en/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "SEO title", name: "seoTitle", widget: "string" }
          - { label: "SEO Description", name: "seoDescription", widget: "text" }
          - {
              label: "Hero",
              name: "hero",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  {
                    label: "Subtitle",
                    name: "subtitle",
                    widget: "string",
                    required: false,
                  },
                ],
            }
          - { label: "Intro", name: "intro", widget: "text", required: false }
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: title, name: title, widget: string }
              - { label: Text, name: text, widget: text }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/en/about-us.md"
        label: "About Us"
        name: "aboutus"
        fields:
          - { label: "SEO title", name: "seoTitle", widget: "string" }
          - { label: "SEO Description", name: "seoDescription", widget: "text" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "pages-pl"
    label: "Pages PL"
    files:
      - file: "src/pages/pl/index.md"
        label: "Strona główna"
        name: "home"
        fields:
          - { label: "SEO title", name: "seoTitle", widget: "string" }
          - { label: "SEO Description", name: "seoDescription", widget: "text" }
          - {
              label: "Hero",
              name: "hero",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  {
                    label: "Subtitle",
                    name: "subtitle",
                    widget: "string",
                    required: false,
                  },
                ],
            }
          - { label: "Intro", name: "intro", widget: "text" }
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: title, name: title, widget: string }
              - { label: Text, name: text, widget: text }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/pl/o-nas.md"
        label: "O nas"
        name: "aboutus"
        fields:
          - { label: "SEO title", name: "seoTitle", widget: "string" }
          - { label: "SEO Description", name: "seoDescription", widget: "text" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: "Has country widget",
              name: "countriesWidget",
              widget: "boolean",
              default: false,
            }
