backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "/src/assets/images"
logo_url: https://bluestarfishtravel.com/_astro/logo.50778641.svg

collections:
  - name: "countries-en" # Used in routes, e.g., /admin/collections/blog
    label: "Countries in English" # Used in the UI
    label_singular: "Country"
    folder: "src/content/country/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    public_folder: "../../../assets/images"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {
          label: "SEO",
          name: "seo",
          widget: "object",
          fields:
            [
              { label: "SEO Title", name: "seoTitle", widget: "string" },
              { label: "SEO Description", name: "seoDesc", widget: "text" },
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sort order", name: "sortOrder", widget: "number" }
      - { label: "Hero Image", name: "cover", widget: "image" }
      - { label: "Widget Image", name: "image", widget: "image" }
      - { label: "Intro", name: "intro", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages-en" # Used in routes, e.g., /admin/collections/blog
    label: "Pages in English" # Used in the UI
    label_singular: "Page"
    folder: "src/content/pages/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    public_folder: "../../../assets/images"
    identifier_field: hero.title
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {
          label: "SEO",
          name: "seo",
          widget: "object",
          fields:
            [
              { label: "SEO Title", name: "seoTitle", widget: "string" },
              { label: "SEO Description", name: "seoDesc", widget: "text" },
            ],
        }
      - {
          label: "Hero",
          name: "hero",
          widget: "object",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              {
                label: "Subtitle",
                name: "subtitle",
                widget: "string",
                required: false,
              },
              { label: "Image", name: "image", widget: "image" },
            ],
        }
      - { label: "Intro", name: "intro", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Countries Widget",
          name: "countriesWidget",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Whatsapp Chat Widget",
          name: "chatWidget",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Contact Form Widget",
          name: "contactForm",
          widget: "boolean",
          default: false,
        }

  - name: "countries-pl" # Used in routes, e.g., /admin/collections/blog
    label: "Kraje po polsku" # Used in the UI
    label_singular: "Kraj"
    folder: "src/content/country/pl" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    public_folder: "../../../assets/images"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {
          label: "SEO",
          name: "seo",
          widget: "object",
          fields:
            [
              { label: "SEO Title", name: "seoTitle", widget: "string" },
              { label: "SEO Description", name: "seoDesc", widget: "text" },
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sort order", name: "sortOrder", widget: "number" }
      - { label: "Hero Image", name: "cover", widget: "image" }
      - { label: "Widget Image", name: "image", widget: "image" }
      - { label: "Intro", name: "intro", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages-pl" # Used in routes, e.g., /admin/collections/blog
    label: "Strony po polsku" # Used in the UI
    label_singular: "Strona"
    folder: "src/content/pages/pl" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    public_folder: "../../../assets/images"
    identifier_field: hero.title
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {
          label: "SEO",
          name: "seo",
          widget: "object",
          fields:
            [
              { label: "SEO Title", name: "seoTitle", widget: "string" },
              { label: "SEO Description", name: "seoDesc", widget: "text" },
            ],
        }
      - {
          label: "Hero",
          name: "hero",
          widget: "object",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              {
                label: "Subtitle",
                name: "subtitle",
                widget: "string",
                required: false,
              },
              { label: "Image", name: "image", widget: "image" },
            ],
        }
      - { label: "Intro", name: "intro", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Countries Widget",
          name: "countriesWidget",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Whatsapp Chat Widget",
          name: "chatWidget",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Contact Form Widget",
          name: "contactForm",
          widget: "boolean",
          default: false,
        }
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "src/data/settings.json"
        description: "General Site Settings"
        fields:
          - { label: "Global title", name: "site_title", widget: "string" }
          - label: "Company Information"
            name: info
            widget: "object"
            fields:
              - { label: "Name", name: name, widget: string }
              - { label: "Address", name: address, widget: string }
              - { label: "City", name: city, widget: string }
              - { label: "Phone", name: phone, widget: string }
              - { label: "Email", name: email, widget: string }
